# Site settings
title: Sloppy Science blog
email: 
description: "Musings of a Bayesian."
baseurl: ""
url: "http://leotd21.github.io"
github_username:  leotd21

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
