# Site settings
title: Approximately Correct blog
email: 
description: "musing over the cuckoo's nest"
baseurl: ""
url: "http://leotd21.github.io"
github_username:  leotd21
future: true

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
